 marginBottom: '24px' }}><label style={{ display: 'block', marginBottom: '8px', color: COLORS.textLight, fontWeight: '500' }}>Tarefa</label><input type="text" value={sessionForm.homework} onChange={e => setSessionForm({...sessionForm, homework: e.target.value})} style={inputStyle} placeholder="Ex: Diário de gatilhos" /></div><div style={{ display: 'flex', gap: '12px' }}><button onClick={() => setShowSessionForm(false)} style={{ flex: 1, padding: '14px', background: COLORS.light, border: 'none', borderRadius: '10px', cursor: 'pointer', color: COLORS.textLight }}>Cancelar</button><button onClick={handleSaveSession} disabled={saving} style={{ ...btnPrimary, flex: 1 }}>{saving ? 'Salvando...' : 'Salvar'}</button></div></div></div>}
      </div>
    );
  };

  const GroupsPage = () => {
    const [showForm, setShowForm] = useState(false);
    const [form, setForm] = useState({ name: '', day_of_week: 1, time: '19:00', meeting_link: '', max_participants: 12 });
    const [saving, setSaving] = useState(false);
    const handleCreate = async () => { setSaving(true); try { await psychologistService.createGroup({ ...form, psychologist_id: user.id, is_active: true }); const { data } = await psychologistService.getMyGroups(user.id); setGroups(data || []); setShowForm(false); setForm({ name: '', day_of_week: 1, time: '19:00', meeting_link: '', max_participants: 12 }); } catch (err) { alert('Erro: ' + err.message); } finally { setSaving(false); } };
    return (
      <div>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px' }}><h1 style={{ fontSize: '28px', color: COLORS.text, margin: 0, fontWeight: '600' }}>Grupos Terapêuticos</h1><button onClick={() => setShowForm(true)} style={btnPrimary}>+ Novo Grupo</button></div>
        {groups.length === 0 ? <div style={{ ...cardStyle, textAlign: 'center', padding: '60px' }}><span style={{ fontSize: '56px' }}>📅</span><p style={{ color: COLORS.textLight, marginTop: '20px', fontSize: '16px' }}>Nenhum grupo cadastrado</p><button onClick={() => setShowForm(true)} style={{ ...btnPrimary, marginTop: '20px' }}>Criar Primeiro Grupo</button></div> : <div style={{ display: 'grid', gap: '20px' }}>{groups.map(g => (<div key={g.id} style={cardStyle}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'start' }}><div><h3 style={{ color: COLORS.text, fontSize: '20px', margin: '0 0 6px', fontWeight: '600' }}>{g.name}</h3><p style={{ color: COLORS.textLight, margin: 0 }}>📅 {['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'][g.day_of_week]} às {g.time?.slice(0,5)}</p><p style={{ color: COLORS.textLight, margin: '8px 0 0', fontSize: '14px' }}>👥 {g.group_participants?.length || 0} / {g.max_participants} participantes</p></div>{g.meeting_link && <a href={g.meeting_link} target="_blank" rel="noopener noreferrer" style={{ ...btnPrimary, padding: '10px 20px', textDecoration: 'none', fontSize: '14px' }}>Iniciar</a>}</div></div>))}</div>}
        {showForm && <div style={{ position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, background: 'rgba(0,0,0,0.5)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000 }}><div style={{ background: COLORS.white, borderRadius: '20px', padding: '32px', width: '100%', maxWidth: '450px' }}><h2 style={{ marginBottom: '24px', color: COLORS.text, fontWeight: '600' }}>Novo Grupo</h2><div style={{ marginBottom: '18px' }}><label style={{ display: 'block', marginBottom: '8px', color: COLORS.textLight, fontWeight: '500' }}>Nome do Grupo *</label><input type="text" placeholder="Ex: Grupo de Apoio Noturno" value={form.name} onChange={e => setForm({...form, name: e.target.value})} style={inputStyle} /></div><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px', marginBottom: '18px' }}><div><label style={{ display: 'block', marginBottom: '8px', color: COLORS.textLight, fontWeight: '500' }}>Dia</label><select value={form.day_of_week} onChange={e => setForm({...form, day_of_week: parseInt(e.target.value)})} style={inputStyle}>{['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'].map((d,i) => <option key={i} value={i}>{d}</option>)}</select></div><div><label style={{ display: 'block', marginBottom: '8px', color: COLORS.textLight, fontWeight: '500' }}>Horário</label><input type="time" value={form.time} onChange={e => setForm({...form, time: e.target.value})} style={inputStyle} /></div></div><div style={{ marginBottom: '18px' }}><label style={{ display: 'block', marginBottom: '8px', color: COLORS.textLight, fontWeight: '500' }}>Máx. Participantes</label><input type="number" value={form.max_participants} onChange={e => setForm({...form, max_participants: parseInt(e.target.value)})} style={inputStyle} /></div><div style={{ marginBottom: '24px' }}><label style={{ display: 'block', marginBottom: '8px', color: COLORS.textLight, fontWeight: '500' }}>Link da Reunião</label><input type="url" placeholder="https://meet.google.com/xxx" value={form.meeting_link} onChange={e => setForm({...form, meeting_link: e.target.value})} style={inputStyle} /></div><div style={{ display: 'flex', gap: '12px' }}><button onClick={() => setShowForm(false)} style={{ flex: 1, padding: '14px', background: COLORS.light, border: 'none', borderRadius: '10px', cursor: 'pointer' }}>Cancelar</button><button onClick={handleCreate} disabled={saving || !form.name} style={{ ...btnPrimary, flex: 1, opacity: (!form.name || saving) ? 0.6 : 1 }}>{saving ? 'Salvando...' : 'Criar'}</button></div></div></div>}
      </div>
    );
  };

  const RequestsPage = () => {
    const handleUpdate = async (id, status) => { await psychologistService.updateContactRequest(id, { status }, user.id); const { data } = await psychologistService.getContactRequests(); setContactRequests(data || []); };
    return (
      <div>
        <h1 style={{ fontSize: '28px', color: COLORS.text, marginBottom: '24px', fontWeight: '600' }}>Solicitações de Contato</h1>
        {contactRequests.length === 0 ? <div style={{ ...cardStyle, textAlign: 'center', padding: '60px' }}><span style={{ fontSize: '56px' }}>📩</span><p style={{ color: COLORS.textLight, marginTop: '20px', fontSize: '16px' }}>Nenhuma solicitação</p></div> : <div style={{ display: 'grid', gap: '16px' }}>{contactRequests.map(r => (<div key={r.id} style={{ ...cardStyle, borderLeft: `4px solid ${r.urgency === 'urgent' ? COLORS.warning : COLORS.primary}`, opacity: r.status === 'pending' ? 1 : 0.6 }}><div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '12px' }}><div><div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}><h3 style={{ fontSize: '18px', color: COLORS.text, margin: 0, fontWeight: '600' }}>{r.name}</h3>{r.urgency === 'urgent' && <span style={{ background: COLORS.warning, color: COLORS.white, padding: '3px 10px', borderRadius: '10px', fontSize: '11px', fontWeight: '500' }}>URGENTE</span>}{r.status !== 'pending' && <span style={{ background: '#e0f5e8', color: COLORS.success, padding: '3px 10px', borderRadius: '10px', fontSize: '11px' }}>Respondido</span>}</div><p style={{ color: COLORS.textLight, fontSize: '14px', margin: '6px 0 0' }}>📞 {r.phone} {r.email && `• ✉️ ${r.email}`}</p></div><span style={{ color: COLORS.textLight, fontSize: '13px' }}>{new Date(r.created_at).toLocaleDateString('pt-BR')}</span></div>{r.message && <div style={{ background: COLORS.light, borderRadius: '12px', padding: '16px', marginBottom: '16px' }}><p style={{ color: COLORS.text, margin: 0, fontStyle: 'italic' }}>"{r.message}"</p></div>}{r.status === 'pending' && <div style={{ display: 'flex', gap: '12px' }}><button onClick={() => handleUpdate(r.id, 'contacted')} style={{ ...btnPrimary, flex: 1, padding: '12px' }}>✓ Marcar Contatado</button><button onClick={() => handleUpdate(r.id, 'archived')} style={{ flex: 1, padding: '12px', background: COLORS.light, border: 'none', borderRadius: '10px', cursor: 'pointer', color: COLORS.textLight }}>Arquivar</button></div>}</div>))}</div>}
      </div>
    );
  };

  const TeamPage = () => {
    const [showForm, setShowForm] = useState(false);
    const [form, setForm] = useState({ email: '', name: '', crp: '', phone: '' });
    const [saving, setSaving] = useState(false);
    const handleCreate = async () => { if (!form.email || !form.name || !form.crp) { alert('Preencha email, nome e CRP'); return; } setSaving(true); try { await supabase.from('psychologists').insert({ ...form, is_active: true }); const { data } = await supabase.from('psychologists').select('*').order('name'); setTeam(data || []); setShowForm(false); setForm({ email: '', name: '', crp: '', phone: '' }); alert('Psicólogo cadastrado! Ele precisará criar uma conta com este email.'); } catch (err) { alert('Erro: ' + err.message); } finally { setSaving(false); } };
    return (
      <div>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px' }}><h1 style={{ fontSize: '28px', color: COLORS.text, margin: 0, fontWeight: '600' }}>Equipe APAJ</h1><button onClick={() => setShowForm(true)} style={btnPrimary}>+ Novo Psicólogo</button></div>
        {team.length === 0 ? <div style={{ ...cardStyle, textAlign: 'center', padding: '60px' }}><span style={{ fontSize: '56px' }}>🏥</span><p style={{ color: COLORS.textLight, marginTop: '20px' }}>Nenhum psicólogo cadastrado</p></div> : <div style={{ display: 'grid', gap: '16px' }}>{team.map(p => (<div key={p.id} style={{ ...cardStyle, display: 'flex', alignItems: 'center', gap: '18px' }}><div style={{ width: '60px', height: '60px', background: `linear-gradient(135deg, ${COLORS.primary} 0%, ${COLORS.primaryDark} 100%)`, borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', color: COLORS.white, fontWeight: '600', fontSize: '20px' }}>{p.name?.split(' ').map(n => n[0]).join('').slice(0, 2)}</div><div style={{ flex: 1 }}><h3 style={{ color: COLORS.text, margin: '0 0 4px', fontSize: '18px', fontWeight: '600' }}>{p.name}</h3><p style={{ color: COLORS.textLight, margin: 0, fontSize: '14px' }}>{p.crp}</p><p style={{ color: COLORS.textLight, margin: '4px 0 0', fontSize: '13px' }}>✉️ {p.email} {p.phone && `• 📞 ${p.phone}`}</p></div><span style={{ padding: '6px 14px', borderRadius: '20px', fontSize: '12px', background: p.is_active ? '#e0f5e8' : '#f0f0f0', color: p.is_active ? COLORS.success : '#888' }}>{p.is_active ? 'Ativo' : 'Inativo'}</span></div>))}</div>}
        {showForm && <div style={{ position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, background: 'rgba(0,0,0,0.5)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000 }}><div style={{ background: COLORS.white, borderRadius: '20px', padding: '32px', width: '100%', maxWidth: '420px' }}><h2 style={{ marginBottom: '24px', color: COLORS.text, fontWeight: '600' }}>Novo Psicólogo</h2><div style={{ marginBottom: '18px' }}><label style={{ display: 'block', marginBottom: '8px', color: COLORS.textLight, fontWeight: '500' }}>Nome Completo *</label><input type="text" placeholder="Dr. João Silva" value={form.name} onChange={e => setForm({...form, name: e.target.value})} style={inputStyle} /></div><div style={{ marginBottom: '18px' }}><label style={{ display: 'block', marginBottom: '8px', color: COLORS.textLight, fontWeight: '500' }}>Email *</label><input type="email" placeholder="joao@apaj.org.br" value={form.email} onChange={e => setForm({...form, email: e.target.value})} style={inputStyle} /></div><div style={{ marginBottom: '18px' }}><label style={{ display: 'block', marginBottom: '8px', color: COLORS.textLight, fontWeight: '500' }}>CRP *</label><input type="text" placeholder="CRP XX/XXXXX" value={form.crp} onChange={e => setForm({...form, crp: e.target.value})} style={inputStyle} /></div><div style={{ marginBottom: '24px' }}><label style={{ display: 'block', marginBottom: '8px', color: COLORS.textLight, fontWeight: '500' }}>Telefone</label><input type="tel" placeholder="(XX) 99999-9999" value={form.phone} onChange={e => setForm({...form, phone: e.target.value})} style={inputStyle} /></div><div style={{ display: 'flex', gap: '12px' }}><button onClick={() => setShowForm(false)} style={{ flex: 1, padding: '14px', background: COLORS.light, border: 'none', borderRadius: '10px', cursor: 'pointer' }}>Cancelar</button><button onClick={handleCreate} disabled={saving} style={{ ...btnPrimary, flex: 1 }}>{saving ? 'Salvando...' : 'Cadastrar'}</button></div></div></div>}
      </div>
    );
  };

  const renderPage = () => {
    switch (currentPage) {
      case 'dashboard': return <Dashboard />;
      case 'patients': return <PatientsList />;
      case 'patient-detail': return <PatientDetail />;
      case 'groups': return <GroupsPage />;
      case 'requests': return <RequestsPage />;
      case 'team': return <TeamPage />;
      default: return <Dashboard />;
    }
  };

  if (loading) return <div style={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', background: COLORS.light }}><p style={{ color: COLORS.primary }}>Carregando...</p></div>;

  return (
    <div style={{ fontFamily: "'Inter', sans-serif", background: COLORS.light, minHeight: '100vh' }}>
      <Sidebar />
      <main style={{ marginLeft: '260px', padding: '32px 40px' }}>{renderPage()}</main>
    </div>
  );
};

export default PsychologistPanel;
